apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-chart.fullname" . }}
data:
    {{- if .Values.config }}
      {{ range $key, $value := .Values.config }}
      {{ $key }} : {{ $value | quote}}
      {{ end }}
    {{- end }}
    {{- if .Values.global.config }}
      {{ range $key, $value := .Values.global.config }}
      {{ $key }} : {{ $value | quote}}
      {{ end }}
    {{- end }}
