apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port  | default 8080  }}
      protocol: TCP
      name: http
  selector:
    {{- include "microservice-chart.selectorLabels" . | nindent 4 }}
